theme: jekyll-theme-minimal
title: Юридические документы LinguaLink
description: Политика конфиденциальности, Условия использования и Лицензионное соглашение для приложения LinguaLink
baseurl: "/Lingua-Link-docs"
url: "https://henek93.github.io"
